# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
POST http://localhost:8000/v1/completions
Content-Type: application/json
Authorization: Bearer 0000000000

{
  "prompt": "What is the capital of France?",
  "model": "aphrodite/TheBloke/Mistral-7B-v0.1-GPTQ",
  "temperature": 0.7,
  "max_tokens": 20
}
