# Test your FastAPI endpoints

GET http://127.0.0.1:8000/v1/models
Accept: application/json
###
GET http://localhost:8000/health
###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
POST http://localhost:8000/v1/completions
Content-Type: application/json
Authorization: Bearer 0000000000

{
  "prompt": "What is the capital of France?",
  "model": "aphrodite/TheBloke/Mistral-7B-v0.1-GPTQ",
  "temperature": 0.7,
  "max_tokens": 20
}
###

POST http://localhost:8000/v1/chat/completions
Content-Type: application/json
Authorization: Bearer 0000000000

{
  "messages":  [
    {"role": "user", "content": "Hello, how are you?"},
    {"role": "assistant", "content": "I'm doing great. How can I help you today?"},
    {"role": "user", "content": "Tell me about antartica"}
],
  "model": "aphrodite/TheBloke/Mistral-7B-v0.1-GPTQ",
  "temperature": 0.7,
  "max_tokens": 100,
  "stop": ["[/INST]", "</s>", "[INST]"]
}

